# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb320d9b8bc8e5036da797d43693e5e8cd7460ff4896725a72706a7f1c2fc8410f985069f9df16ff3f49ab9deeed2959e7e6193685a534242a096f889f1b6228

test:
  secret_key_base: 676235cfa31fac0a21d91211a3c5fb3f91b2e51437b51979e131f4bdb158895c8a04d3ccec75c60a32437b1c74ebe1731717e06a0b5278dd97bb4799765c02d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
